name: GitHub Actions Demo
run-name: ${{ github.actor}} is testing out Github Action 🚀
on: [push]
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name}} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name:  Checkout Repository code
              uses: actions/checkout@v5
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - run: echo "🖥️ The workflow is now ready to test your code on the runner."
            - name: List files in the repo
              run: |
                 ls ${{github.workspace}}
            - run: echo "🍏 This job's status is ${{ job.status }}."

            - name: Create a readme file
              run: |
                 echo '#websites' > README.md
                 echo "" >> README.md
                 echo "A brief description of the project. " >> README.md
                  # Add more content as needed using additional echo commands
            - name: Commit and push ReadMe
              run: |
                 git config --global user.name "DICKSON39"
                 git config --global user.email "dicksonndumia19@gmail.com"
                 git add README.md
                  git commit -m "Auto-generate README"
                  git push